import { NodeFormFieldsMap, FormFieldProps } from "../";

const locationInputs: FormFieldProps[] = [
  {
    name: "chr",
    label: "Chromosome",
    inputType: "combobox",
    options: [
      { value: "X" },
      { value: "Y" },
      ...new Array(22)
        .fill(null)
        .map((_, i) => ({ value: (i + 1).toString() })),
    ],
  },
  { label: "Start", name: "start", inputType: "input", type: "number" },
  { label: "End", name: "end", inputType: "input", type: "number" },
];

const formFields: NodeFormFieldsMap = {
  enhancer: locationInputs,
  super_enhancer: locationInputs,
  promoter: locationInputs,
  tad: locationInputs,
  tfbs: locationInputs,
  unberon: [{ label: "Name", name: "term_name", inputType: "input" }],
  clo: [{ label: "Name", name: "term_name", inputType: "input" }],
  cl: [{ label: "Name", name: "term_name", inputType: "input" }],
  efo: [{ label: "Name", name: "term_name", inputType: "input" }],
  bto: [{ label: "Name", name: "term_name", inputType: "input" }],
  motif: [{ label: "Name", name: "tf_name", inputType: "input" }],
  pathway: [{ label: "Name", name: "pathway_name", inputType: "input" }],
  gene: [
    { label: "Name", name: "gene_name", inputType: "input" },
    {
      label: "Type",
      name: "gene_type",
      inputType: "combobox",
      options: [
        { value: "lncRNA" },
        { value: "snRNA" },
        { value: "snoRNA" },
        { value: "processed_pseudogene" },
        { value: "transcribed_unprocessed_pseudogene" },
        { value: "protein_coding" },
        { value: "unprocessed_pseudogene" },
        { value: "TEC" },
        { value: "miRNA" },
        { value: "rRNA_pseudogene" },
        { value: "scaRNA" },
        { value: "misc_RNA" },
        { value: "transcribed_processed_pseudogene" },
        { value: "transcribed_unitary_pseudogene" },
        { value: "rRNA" },
        { value: "unitary_pseudogene" },
        { value: "pseudogene" },
        { value: "IG_V_pseudogene" },
        { value: "scRNA" },
        { value: "sRNA" },
        { value: "IG_C_gene" },
        { value: "IG_J_gene" },
        { value: "IG_V_gene" },
        { value: "translated_processed_pseudogene" },
        { value: "ribozyme" },
        { value: "vault_RNA" },
        { value: "TR_V_gene" },
        { value: "TR_V_pseudogene" },
        { value: "TR_C_gene" },
        { value: "TR_J_gene" },
        { value: "TR_D_gene" },
        { value: "IG_C_pseudogene" },
        { value: "TR_J_pseudogene" },
        { value: "IG_J_pseudogene" },
        { value: "IG_D_gene" },
        { value: "IG_pseudogene" },
        { value: "artifact" },
        { value: "Mt_tRNA" },
        { value: "Mt_rRNA" },
      ],
    },
    ...locationInputs,
  ],
  protein: [{ label: "Name", name: "protein_name", inputType: "input" }],
  transcript: [
    { label: "Gene name", name: "gene_name", inputType: "input" },
    { label: "Transcript name", name: "transcript_name", inputType: "input" },
    {
      label: "Type",
      name: "transcript_type",
      inputType: "combobox",
      options: [
        { value: "processed_transcript" },
        { value: "lncRNA" },
        { value: "transcribed_unprocessed_pseudogene" },
        { value: "unprocessed_pseudogene" },
        { value: "miRNA" },
        { value: "nonsense_mediated_decay" },
        { value: "transcribed_unitary_pseudogene" },
        { value: "protein_coding" },
        { value: "protein_coding_CDS_not_defined" },
        { value: "retained_intron" },
        { value: "misc_RNA" },
        { value: "processed_pseudogene" },
        { value: "transcribed_processed_pseudogene" },
        { value: "snRNA" },
        { value: "snoRNA" },
        { value: "TEC" },
        { value: "rRNA_pseudogene" },
        { value: "scaRNA" },
        { value: "non_stop_decay" },
        { value: "protein_coding_LoF" },
        { value: "unitary_pseudogene" },
        { value: "pseudogene" },
        { value: "rRNA" },
        { value: "IG_V_pseudogene" },
        { value: "scRNA" },
        { value: "IG_V_gene" },
        { value: "IG_C_gene" },
        { value: "IG_J_gene" },
        { value: "sRNA" },
        { value: "ribozyme" },
        { value: "translated_processed_pseudogene" },
        { value: "vault_RNA" },
        { value: "TR_C_gene" },
        { value: "TR_J_gene" },
        { value: "TR_V_gene" },
        { value: "TR_V_pseudogene" },
        { value: "TR_D_gene" },
        { value: "IG_C_pseudogene" },
        { value: "TR_J_pseudogene" },
        { value: "IG_J_pseudogene" },
        { value: "IG_D_gene" },
        { value: "IG_pseudogene" },
        { value: "artifact" },
        { value: "Mt_tRNA" },
        { value: "Mt_rRNA" },
      ],
    },
  ],
  exon: [
    { label: "Gene ID", name: "gene_id", inputType: "input" },
    { label: "Transcript ID", name: "transcript_id", inputType: "input" },
    { label: "Exon number", name: "exon_number", inputType: "input" },
    ...locationInputs,
  ],
  snp: [
    { label: "Ref", name: "ref", inputType: "input" },
    { label: "Alt", name: "alt", inputType: "input" },
    { label: "Caf_ref", name: "caf_ref", inputType: "input" },
    { label: "Caf_alt", name: "caf_alt", inputType: "input" },
    ...locationInputs,
  ],
  sv: [
    {
      label: "Variant type",
      name: "variant_type",
      inputType: "combobox",
      options: [
        { value: "duplication" },
        { value: "deletion" },
        { value: "loss" },
        { value: "gain+loss" },
        { value: "complex" },
        { value: "gain" },
        { value: "insertion" },
        { value: "inversion" },
        { value: "tandem duplication" },
        { value: "sva insertion" },
        { value: "alu insertion" },
        { value: "novel sequence insertion" },
        { value: "sequence alteration" },
        { value: "mobile element insertion" },
        { value: "mobile element deletion" },
        { value: "line1 deletion" },
        { value: "alu deletion" },
        { value: "line1 insertion" },
        { value: "sva deletion" },
        { value: "herv deletion" },
        { value: "herv insertion" },
        { value: "copy number variation" },
      ],
    },
    ...locationInputs,
  ],
  non_coding_rna: [
    {
      label: "RNA type",
      name: "rna_type",
      inputType: "combobox",
      options: [
        { value: "piRNA" },
        { value: "tRNA" },
        { value: "SRP_RNA" },
        { value: "lncRNA" },
        { value: "sRNA" },
        { value: "miRNA" },
        { value: "pre_miRNA" },
        { value: "snRNA" },
        { value: "misc_RNA" },
        { value: "snoRNA" },
        { value: "precursor_RNA" },
        { value: "scRNA" },
        { value: "antisense_RNA" },
        { value: "ncRNA" },
        { value: "Y_RNA" },
        { value: "circRNA" },
        { value: "scaRNA" },
        { value: "rRNA" },
        { value: "ribozyme" },
        { value: "other" },
        { value: "guide_RNA" },
        { value: "autocatalytically_spliced_intron" },
        { value: "RNase_P_RNA" },
        { value: "vault_RNA" },
        { value: "RNase_MRP_RNA" },
        { value: "hammerhead_ribozyme" },
        { value: "telomerase_RNA" },
      ],
    },
    ...locationInputs,
  ],
  go: [
    { label: "Term name", name: "term_name", inputType: "input" },
    {
      label: "Subontology",
      name: "subontology",
      inputType: "combobox",
      options: [
        { value: "biological_process" },
        { value: "molecular_function" },
        { value: "cellular_component" },
        { value: "external" },
        { value: "gene_ontology" },
      ],
    },
  ],
};

export default formFields;
